#!/usr/bin/env python3
"""Regression tests for the bounded DeepSeek Harness worktree runner."""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
RUNNER = SCRIPT_DIR / "run-dsh-worker.sh"


def run(*args: str, cwd: Path | None = None, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, cwd=cwd, env=env, text=True, capture_output=True, check=False)


def write_packet(path: Path, allowed: str = "generated.txt") -> None:
    path.write_text(
        f"""# Task Packet

## Objective

Create the requested fixture.

## Dependencies

none

## Allowed paths

- {allowed}

## Forbidden paths

- .git/**

## Acceptance criteria

- The fixture exists.

## Required verification

- test -f {allowed.rstrip('/**')}

## Explicit non-goals

- Do not edit other files.

## Nested delegation

forbidden

## HEAD-only dependency

yes
""",
        encoding="utf-8",
    )


class DshRunnerTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tempdir = tempfile.TemporaryDirectory()
        self.root = Path(self.tempdir.name)
        self.repo = self.root / "repo"
        self.repo.mkdir()
        self.assertEqual(run("git", "init", "-q", str(self.repo)).returncode, 0)
        (self.repo / "README.md").write_text("fixture\n", encoding="utf-8")
        self.assertEqual(run("git", "-C", str(self.repo), "add", "README.md").returncode, 0)
        commit = run(
            "git",
            "-C",
            str(self.repo),
            "-c",
            "user.name=Test",
            "-c",
            "user.email=test@example.com",
            "commit",
            "-qm",
            "fixture",
        )
        self.assertEqual(commit.returncode, 0, commit.stderr)

        self.packet = self.root / "task.md"
        write_packet(self.packet)
        self.session_root = self.root / "dsh-sessions"
        self.session_root.mkdir()
        self.fake_dsh = self.root / "fake-dsh.sh"
        self.fake_dsh.write_text(
            """#!/usr/bin/env bash
if [[ "$1" != "--profile" || "$2" != "headless" ]]; then
  echo "headless profile is required" >&2
  exit 88
fi
if [[ "${3:-}" == "--help" ]]; then
  exit "${FAKE_DSH_PREFLIGHT_EXIT:-0}"
fi
if [[ "${3:-}" == "--dump-config" ]]; then
  printf '%s\n' 'provider:' '  model: deepseek-v4-flash'
  exit "${FAKE_DSH_CONFIG_EXIT:-0}"
fi
printf '%s\n' 'generated by fake DeepSeek' > "${FAKE_DSH_PATH:-generated.txt}"
if [[ "${FAKE_DSH_STAGE:-0}" == "1" ]]; then
  git add -- "${FAKE_DSH_PATH:-generated.txt}"
fi
if [[ "${FAKE_DSH_NO_SESSION:-0}" != "1" ]]; then
  run_id="$(printf '%s\n' "${3:-}" | sed -n 's/^Worker receipt run id: //p' | head -1)"
  printf '{"run_id":"%s","model":"deepseek-v4-flash","reasoningEffort":"on","record":{"rows":{"tokenUsage":{"val":{"totals":{"uncachedInputTokens":120,"outputTokens":15,"cacheReadTokens":30,"cacheWriteTokens":5}}}}}}\n' "$run_id" > "${FAKE_DSH_SESSION_ROOT}/session-${run_id}.json"
fi
printf '%s\n' 'reasoning' >&2
printf '%s\n' 'completed'
exit "${FAKE_DSH_EXIT:-0}"
""",
            encoding="utf-8",
        )
        self.fake_dsh.chmod(0o755)

    def tearDown(self) -> None:
        self.tempdir.cleanup()

    def invoke(self, output: Path, **overrides: str) -> subprocess.CompletedProcess[str]:
        env = dict(os.environ)
        env["DSH_BIN"] = str(self.fake_dsh)
        env["DSH_SESSION_ROOT"] = str(self.session_root)
        env["FAKE_DSH_SESSION_ROOT"] = str(self.session_root)
        env.update(overrides)
        return run(
            "bash",
            str(RUNNER),
            "--cwd",
            str(self.repo),
            "--task-file",
            str(self.packet),
            "--output-dir",
            str(output),
            env=env,
        )

    def test_runner_exports_patch_and_leaves_main_workspace_unchanged(self) -> None:
        output = self.root / "artifacts"
        result = self.invoke(output)
        self.assertEqual(result.returncode, 0, result.stderr)
        for name in (
            "final.txt",
            "reasoning.log",
            "status.txt",
            "changed-paths.txt",
            "changes.patch",
            "exit-code",
            "scope-check.txt",
            "worker-receipt.json",
            "manifest.json",
        ):
            self.assertTrue((output / name).exists(), name)
        self.assertIn("generated.txt", (output / "changes.patch").read_text(encoding="utf-8"))
        self.assertFalse((self.repo / "generated.txt").exists())
        manifest = json.loads((output / "manifest.json").read_text(encoding="utf-8"))
        receipt = json.loads((output / "worker-receipt.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["worker"], "deepseek-harness")
        self.assertEqual(manifest["profile"], "headless")
        self.assertEqual(manifest["actual_model"], "deepseek-v4-flash")
        self.assertEqual(manifest["usage"]["input_tokens"], 155)
        self.assertEqual(manifest["usage"]["output_tokens"], 15)
        self.assertEqual(manifest["usage"]["total_tokens"], 170)
        self.assertTrue(manifest["metadata_complete"])
        self.assertEqual(receipt["reasoning_effort"], "on")
        self.assertEqual(receipt["fork_turns"], "not-applicable")
        self.assertTrue(manifest["scope_ok"])
        self.assertTrue(manifest["worktree_cleaned"])

    def test_worker_exit_code_is_preserved(self) -> None:
        output = self.root / "blocked-artifacts"
        result = self.invoke(output, FAKE_DSH_EXIT="3")
        self.assertEqual(result.returncode, 3, result.stderr)
        self.assertEqual((output / "exit-code").read_text(encoding="utf-8").strip(), "3")

    def test_staged_change_is_exported_and_scope_checked(self) -> None:
        output = self.root / "staged-artifacts"
        result = self.invoke(output, FAKE_DSH_STAGE="1")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual((output / "changed-paths.txt").read_text(encoding="utf-8"), "generated.txt\n")
        self.assertIn("generated.txt", (output / "changes.patch").read_text(encoding="utf-8"))

    def test_out_of_scope_change_is_rejected(self) -> None:
        output = self.root / "scope-artifacts"
        result = self.invoke(output, FAKE_DSH_PATH="forbidden.txt")
        self.assertEqual(result.returncode, 65, result.stderr)
        self.assertIn("outside allowed scope", (output / "scope-check.txt").read_text(encoding="utf-8"))

    def test_failed_headless_preflight_is_rejected(self) -> None:
        output = self.root / "preflight-artifacts"
        result = self.invoke(output, FAKE_DSH_PREFLIGHT_EXIT="4")
        self.assertEqual(result.returncode, 69)
        self.assertIn("headless profile preflight failed", result.stderr)

    def test_success_without_usage_metadata_is_rejected(self) -> None:
        output = self.root / "missing-metadata-artifacts"
        result = self.invoke(output, FAKE_DSH_NO_SESSION="1")
        self.assertEqual(result.returncode, 75, result.stderr)
        manifest = json.loads((output / "manifest.json").read_text(encoding="utf-8"))
        receipt = json.loads((output / "worker-receipt.json").read_text(encoding="utf-8"))
        self.assertFalse(manifest["metadata_complete"])
        self.assertEqual(receipt["status"], "metadata-incomplete")


if __name__ == "__main__":
    unittest.main()
