#!/usr/bin/env python3
"""Regression tests for the bounded Kimi worktree runner."""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

from task_packet import PacketError, load_packet, scope_errors


SCRIPT_DIR = Path(__file__).resolve().parent
RUNNER = SCRIPT_DIR / "run-kimi-worker.sh"


def run(*args: str, cwd: Path | None = None, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, cwd=cwd, env=env, text=True, capture_output=True, check=False)


def write_packet(path: Path, allowed: str = "generated.txt") -> None:
    path.write_text(
        f"""# Task Packet

## Objective

Create the requested fixture.

## Dependencies

none

## Allowed paths

- {allowed}

## Forbidden paths

- .git/**

## Acceptance criteria

- The fixture exists.

## Required verification

- test -f {allowed.rstrip('/**')}

## Explicit non-goals

- Do not edit other files.

## Nested delegation

forbidden

## HEAD-only dependency

yes
""",
        encoding="utf-8",
    )


class TaskPacketTests(unittest.TestCase):
    def test_valid_packet_and_scope(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            packet = Path(tmp) / "task.md"
            write_packet(packet, "src/**")
            allowed, forbidden = load_packet(packet)
            self.assertEqual(allowed, ["src/**"])
            self.assertEqual(scope_errors(["src/example.py"], allowed, forbidden), [])
            self.assertEqual(scope_errors(["README.md"], allowed, forbidden), ["path outside allowed scope: README.md"])

    def test_unbounded_allowed_path_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            packet = Path(tmp) / "task.md"
            write_packet(packet, "**")
            with self.assertRaises(PacketError):
                load_packet(packet)

    def test_nested_delegation_must_be_forbidden(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            packet = Path(tmp) / "task.md"
            write_packet(packet)
            packet.write_text(
                packet.read_text(encoding="utf-8").replace(
                    "## Nested delegation\n\nforbidden",
                    "## Nested delegation\n\nallowed",
                ),
                encoding="utf-8",
            )
            with self.assertRaisesRegex(PacketError, "Nested delegation must be forbidden"):
                load_packet(packet)


class KimiRunnerTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tempdir = tempfile.TemporaryDirectory()
        self.root = Path(self.tempdir.name)
        self.repo = self.root / "repo"
        self.repo.mkdir()
        self.assertEqual(run("git", "init", "-q", str(self.repo)).returncode, 0)
        (self.repo / "README.md").write_text("fixture\n", encoding="utf-8")
        self.assertEqual(run("git", "-C", str(self.repo), "add", "README.md").returncode, 0)
        commit = run(
            "git",
            "-C",
            str(self.repo),
            "-c",
            "user.name=Test",
            "-c",
            "user.email=test@example.com",
            "commit",
            "-qm",
            "fixture",
        )
        self.assertEqual(commit.returncode, 0, commit.stderr)

        self.packet = self.root / "task.md"
        write_packet(self.packet)
        self.fake_kimi = self.root / "fake-kimi.sh"
        self.fake_kimi.write_text(
            """#!/usr/bin/env bash
if [[ "${KIMI_CODE_EXPERIMENTAL_FLAG:-}" != "1" ]]; then
  echo "KIMI_CODE_EXPERIMENTAL_FLAG is required" >&2
  exit 88
fi
printf '%s\n' 'generated by fake Kimi' > "${FAKE_KIMI_PATH:-generated.txt}"
printf '%s\n' '{"type":"assistant","content":"done"}'
exit "${FAKE_KIMI_EXIT:-0}"
""",
            encoding="utf-8",
        )
        self.fake_kimi.chmod(0o755)

    def tearDown(self) -> None:
        self.tempdir.cleanup()

    def invoke(self, output: Path, **overrides: str) -> subprocess.CompletedProcess[str]:
        env = dict(os.environ)
        env["KIMI_BIN"] = str(self.fake_kimi)
        env.update(overrides)
        return run(
            "bash",
            str(RUNNER),
            "--cwd",
            str(self.repo),
            "--task-file",
            str(self.packet),
            "--output-dir",
            str(output),
            env=env,
        )

    def test_runner_exports_patch_and_leaves_main_workspace_unchanged(self) -> None:
        output = self.root / "artifacts"
        result = self.invoke(output)
        self.assertEqual(result.returncode, 0, result.stderr)
        for name in (
            "events.jsonl",
            "stderr.log",
            "status.txt",
            "changed-paths.txt",
            "changes.patch",
            "exit-code",
            "scope-check.txt",
            "manifest.json",
        ):
            self.assertTrue((output / name).exists(), name)
        self.assertIn("generated.txt", (output / "changes.patch").read_text(encoding="utf-8"))
        self.assertFalse((self.repo / "generated.txt").exists())
        manifest = json.loads((output / "manifest.json").read_text(encoding="utf-8"))
        self.assertTrue(manifest["scope_ok"])
        self.assertTrue(manifest["worktree_cleaned"])
        worktrees = run("git", "-C", str(self.repo), "worktree", "list", "--porcelain")
        self.assertEqual(worktrees.stdout.count("worktree "), 1)

    def test_goal_exit_code_is_preserved(self) -> None:
        output = self.root / "blocked-artifacts"
        result = self.invoke(output, FAKE_KIMI_EXIT="3")
        self.assertEqual(result.returncode, 3, result.stderr)
        self.assertEqual((output / "exit-code").read_text(encoding="utf-8").strip(), "3")

    def test_out_of_scope_change_is_rejected(self) -> None:
        output = self.root / "scope-artifacts"
        result = self.invoke(output, FAKE_KIMI_PATH="forbidden.txt")
        self.assertEqual(result.returncode, 65, result.stderr)
        self.assertIn("outside allowed scope", (output / "scope-check.txt").read_text(encoding="utf-8"))

    def test_dirty_allowed_path_blocks_dispatch(self) -> None:
        (self.repo / "generated.txt").write_text("user change\n", encoding="utf-8")
        output = self.root / "dirty-artifacts"
        result = self.invoke(output)
        self.assertEqual(result.returncode, 65)
        self.assertIn("allowed path has uncommitted changes", result.stderr)

    def test_non_git_cwd_is_rejected(self) -> None:
        nongit = self.root / "nongit"
        nongit.mkdir()
        output = self.root / "nongit-artifacts"
        env = dict(os.environ)
        env["KIMI_BIN"] = str(self.fake_kimi)
        result = run(
            "bash",
            str(RUNNER),
            "--cwd",
            str(nongit),
            "--task-file",
            str(self.packet),
            "--output-dir",
            str(output),
            env=env,
        )
        self.assertEqual(result.returncode, 66)
        self.assertIn("not inside a Git repository", result.stderr)


if __name__ == "__main__":
    unittest.main()
